# Generated by Django 3.2.12 on 2024-01-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finch',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='finch',
            name='description',
        ),
        migrations.AddField(
            model_name='finch',
            name='bird',
            field=models.BooleanField(default=False),
        ),
    ]
